# Site settings
title: Axis Maps
email: info@axismaps.com
description: Axis Maps - Data. Design. Code.
baseurl: ""
url: "http://beta.axismaps.com"
easyurl: "http://beta.axismaps.com"
paginate: 10
paginate_path: "/blog/page:num/"
permalink: "/blog/:year/:month/:title/"
collections:
  projects:
    output: true
    layout: project
    permalink: /projects/:path/
  guide:
    output: true
    layout: guide
    permalink: /guide/:title/

# Build settings
markdown: kramdown
highlighter: rouge
gems: 
  - jekyll-paginate
  - jekyll-gist
