# Site settings
title: Axis Maps
email: info@axismaps.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://axismaps.s3-website-eu-west-1.amazonaws.com/" # the base hostname & protocol for your site
easyurl: "http://www.axismaps.com"
paginate: 5
paginate_path: "/blog/page:num/"
permalink: "/blog/:year/:month/:title/"
collections:
  projects:
    output: true
    layout: project
    permalink: /projects/:path/
  guides:
    output: true
    layout: guide
    permalink: /guide/:path/

# Build settings
markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
