# Site settings
title: Axis Maps
email: info@axismaps.com
description: Bringing the traditions of cartography to the web
baseurl: ""
url: "https://www.axismaps.com"
easyurl: "https://www.axismaps.com"
twitter:
  username: axismaps
logo: /images/logo.png
paginate: 10
paginate_path: "/blog/page:num/"
permalink: "/blog/:year/:month/:title/"
collections:
  projects:
    output: true
    layout: project
    permalink: /projects/:path/
  guide:
    output: true
    layout: guide
    permalink: /guide/:categories/:slug/

# Build settings
markdown: kramdown
highlighter: rouge
plugins: 
  - jekyll-paginate
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
